// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MasterdataRollingStockNumberInput struct {
	Number         pgtype.Text
	NumberTypeCode pgtype.Text
	RwAdminID      pgtype.Int8
}
